from app.services.ai_service import classify_image, download_image_temp,assess_severity, calculate_priority
from app.services.duplicate_service import find_duplicate, haversine_distance_meters
from app.services.workflow_service import transition_report_status, STATE_TRANSITIONS
from app.services.notification_service import create_notification